<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php
    $this->headTitle()->append('Zend Framework');
    $this->headTitle()->setSeparator(' - ');
    echo $this->headTitle();
    echo $this->headMeta('Reginaldo Castardo', 'author'),PHP_EOL;;
    //Bootstrap
    echo $this->headLink()->prependStylesheet($this->baseUrl('/assets/bootstrap/css/bootstrap.css')),PHP_EOL;;
    //echo $this->headScript()->prependFile($this->baseUrl('scripts/jquery/jquery-1.6.1.min.js')),PHP_EOL;;
    ?>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!-- [if lt IE 9] -->
    <?php echo $this->headScript()->prependFile('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js'),PHP_EOL; ?>
    <?php echo $this->headScript()->prependFile('https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js'),PHP_EOL; ?>
    <!-- [endif] -->

    <!-- custom.css-->
    <?php echo $this->headLink()->appendStylesheet('/assets/css/custom.css') ?>


</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Zend Learning</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url(array('controller'=>'person', 'action'=>'index'), 'default', true)?>">Person</a></li>
            </ul>


            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'register'), 'default', true)?>">Register</a></li>
                <li><a href="<?php echo $this->url(array('controller'=>'user', 'action'=>'login'), 'default', true)?>">Login</a></li>
            </ul>


        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


<?php echo $this->layout()->content; ?>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<?php echo $this->inlineScript()->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js') ?>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<?php echo $this->inlineScript()->prependFile('/assets/bootstrap/js/bootstrap.js') ?>
<!-- custom.js -->
<?php echo $this->inlineScript()->prependFile('/assets/js/custom.js') ?>



</body>
</html>
