<?php echo $this->headTitle('Person - '); ?>

<h2>List Person</h2>
<hr>

<a href="<?= $this->url(array('controller' => 'person', 'action' => 'create'), 'default', true) ?>"
   class="btn btn-info"><i class="glyphicon glyphicon-plus"></i> New</a><br><br>

<table class="table table-bordered table-striped">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Age</th>
        <th>Sex</th>
        <th>Action</th>
    </tr>
    <?php foreach ($this->personArray as $person): ?>
        <tr>
            <td><?= $person->getId() ?></td>
            <td><?= $person->getName() ?></td>
            <td><?= $person->getAge() ?></td>
            <td><?= $person->getSex() ?></td>
            <td>
                <a href="<? ?>" class="btn btn-info btn-xs" title="Show"><i class="glyphicon glyphicon-eye-open"></i>
                </a>
                <a href="<? ?>" class="btn btn-info btn-xs" title="Edit"><i class="glyphicon glyphicon-pencil"></i> </a>
                <a href="<? ?>" class="btn btn-info btn-xs confirm-action"
                   data-message="Are you sure you want to delete this person?" title="Delete"><i
                        class="glyphicon glyphicon-trash"></i> </a>
            </td>
        </tr>
    <?php endforeach ?>
</table>